name: "Bicep Deploy Workflow"

on:
 push:
   branches:
     - main

env:
  subscriptionId: 82be12b4-2c43-4a1f-9909-daee4288ea1a 

jobs:

  bicepAZCliDeploy:
    # The type of runner that the job will run on
    name: Bicep AZ CLI Deploy Job
    runs-on: ubuntu-latest

    env:
      resource_group_name: rg-bicep-azcli-githubactions
      location: northeurope
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v1
        with: 
           creds: ${{ secrets.AZURE_CREDENTIALS }}

      
      - name: Deploy  Resource Group
        uses: Azure/cli@1.0.4
        with: 
          inlinescript:  az deployment sub create \
                         --name ${{env.resource_group_name}} \
                         --location "${{env.location}}"  \
                         --template-file ./bicep-templates/resourcegroup.bicep \
                         --parameters  resourcegroupname=${{ env.resource_group_name}} location="${{env.location}}"
 
      - name: Deploy  virtual network
        uses: Azure/cli@1.0.4
        with: 
          inlinescript: az deployment group create --resource-group ${{ env.resource_group_name}} --template-file ./bicep-templates/virtualnetwork.bicep  --paramters vNetPrefix=bicepazcli  location="${{env.location}}"

  bicepArmDeployDeploy:
    # The type of runner that the job will run on
    name: Bicep arm-deploy Deploy Job
    runs-on: ubuntu-latest

    env:
      resource_group_name: rg-bicep-armdeploy-githubactions
      location: northeurope
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v1
        with: 
           creds: ${{ secrets.AZURE_CREDENTIALS }}
                 
                 
      - name: Deploy  Resource group
        uses: Azure/arm-deploy@v1
        with: 
          scope: subscription
          region: ${{env.location}}   
          subscriptionId: ${{env.subscriptionId}}  
          deploymentName: ${{ env.resource_group_name }}
          template: ./bicep-template/resourcegroup.bicep
          parameters:  location=${{env.location}} resourcegroupname=${{ env.resource_group_name }}
          
      - name: Deploy vnet
        uses: Azure/arm-deploy@v1
        id: storageAccountDeploy
        with: 
          scope: resourcegroup
          resourceGroupName: ${{ env.resource_group_name }}
          subscriptionId: ${{env.subscriptionId}}    
          template: ./bicep-template/virtualnetwork.bicep
          parameters: vNetPrefix=biceparmdeploy  location=${{env.location}}
